services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - ${MQTT_BROKER_PORT}:21883
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: unless-stopped
  kubios-proxy:
    image: josephhotchkiss/kubios-proxy
    depends_on:
      - mqtt
    ports:
      - 80:80
    environment:
      - MQTT_BROKER_IP=${MQTT_BROKER_IP}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
    volumes:
      - ./kubios-proxy:/kubios-proxy/config
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - ./pushgateway:/pushgateway
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  grafana_data:
