global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: 'pushgateway'
  scrape_interval: 1s
  scrape_timeout: 1s
  honor_labels: true
  static_configs:
  - targets:
    - pushgateway:9091
